
import dd.ConnectionProvider;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author rubai
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public static String sname;
    public static String uname;
    public Order()
    {
        initComponents();
        load();
    }
    public Order(String n) {
        initComponents();
        uname = n;
        load();
    }
    public Order(String n,String s) {
        initComponents();
        uname = n;
        sname = s;
        combo_name.getModel().setSelectedItem(sname);
        load();
    }
    
    public void load()
    {
         try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("select service_name from services");

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("service_name");
                combo_name.addItem(name);
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        combo_name = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combo_p = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();
        address = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        service_charge = new javax.swing.JLabel();
        com_time = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1464, 29, -1, -1));

        combo_name.setBackground(new java.awt.Color(222, 235, 248));
        combo_name.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        combo_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add here-->" }));
        combo_name.setOpaque(true);
        combo_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combo_nameMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                combo_nameMouseReleased(evt);
            }
        });
        combo_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_nameActionPerformed(evt);
            }
        });
        combo_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                combo_nameKeyReleased(evt);
            }
        });
        jPanel1.add(combo_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 350, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutPic/yy.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 221, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutPic/tt.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 220, -1, 351));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 116, 188));
        jLabel2.setText("Book Your Service");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 460, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel4.setText("Service name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 129, 36));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setText(" Description:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 150, 36));

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel7.setText(" Service Charge:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 140, 36));

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel8.setText(" Select Date:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 120, 36));

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel9.setText(" Expected Time:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 150, 36));

        combo_p.setBackground(new java.awt.Color(222, 235, 248));
        combo_p.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        combo_p.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Normal", "High" }));
        combo_p.setOpaque(true);
        jPanel1.add(combo_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 350, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel10.setText(" Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 150, 36));

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel11.setText(" Priority:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 150, 36));

        rSMaterialButtonCircle1.setText("Request Service");
        rSMaterialButtonCircle1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 690, 520, 90));

        address.setBackground(new java.awt.Color(222, 235, 248));
        address.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 350, 40));

        date.setBackground(new java.awt.Color(222, 235, 248));
        date.setDateFormatString("yyyy-MM-dd");
        date.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 350, 40));

        description.setBackground(new java.awt.Color(222, 235, 248));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        description.setRows(3);
        jScrollPane1.setViewportView(description);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 350, 90));

        service_charge.setBackground(new java.awt.Color(222, 235, 248));
        service_charge.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        service_charge.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        service_charge.setOpaque(true);
        jPanel1.add(service_charge, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 350, 40));

        com_time.setBackground(new java.awt.Color(222, 235, 248));
        com_time.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        com_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Time---", "8.00 am", "9.00 am", "10.00 am", "11.00 am", "12.00 pm", "1.00 pm", "2.00 pm", "3.00 pm", "4.00 pm", "5.00 pm", "6.00 pm", "7.00 pm", "8.00 pm", "9.00 pm", "10.00 pm", "11.00 pm" }));
        jPanel1.add(com_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 350, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close Application", "Select", JOptionPane.YES_NO_OPTION);
//        if (a == 0)
//            System.exit(0);
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
        try {
           
           Connection c = ConnectionProvider.getcon();
           String sql = "insert into up (user, service, charge, date, time, address, priority, description,status,workerid) values(?,?,?,?,?,?,?,?,?,?)";
           PreparedStatement ptst = c.prepareStatement(sql);
           ptst.setString(1,uname);
           ptst.setString(2, sname);
           ptst.setString(3, service_charge.getText());
           ptst.setString(4, ((JTextField)date.getDateEditor().getUiComponent()).getText());
           ptst.setString(5,com_time.getSelectedItem().toString());
           ptst.setString(6,address.getText());
           ptst.setString(7,combo_p.getSelectedItem().toString());
           ptst.setString(8,description.getText());
           ptst.setString(9,"Requested");
           ptst.setString(10,"Not Assigned");
           ptst.executeUpdate();
           c.close();
           new confirm(uname,sname).setVisible(true);
           this.dispose();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void combo_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_nameKeyReleased

    private void combo_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_nameActionPerformed
        // TODO add your handling code here:
        
        sname = combo_name.getSelectedItem().toString();
        
        try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("select *from services where service_name = ?");
            pst.setString(1, sname);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                service_charge.setText(rs.getString("service_charge"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo_nameActionPerformed

    private void combo_nameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_nameMouseReleased

    }//GEN-LAST:event_combo_nameMouseReleased

    private void combo_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_nameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_nameMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JComboBox<String> com_time;
    private javax.swing.JComboBox<String> combo_name;
    private javax.swing.JComboBox<String> combo_p;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextArea description;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JLabel service_charge;
    // End of variables declaration//GEN-END:variables
}
