
import dd.ConnectionProvider;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rubai
 */
public class orderUser extends javax.swing.JFrame {

    /**
     * Creates new form AdminService
     */
    public static String name;
    public void showtable(String name)
    {
        try {
            // TODO add your handling code here:
            String s = "Requested";
           Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sp","root","15177");
           String sql = "select *from up where user = ? and (status = ? or status = ?) order by idup desc";
           PreparedStatement ptst = c.prepareStatement(sql);
           ptst.setString(1, name);
           ptst.setString(2, s);
           ptst.setString(3, "Assigned");
           ResultSet rs = ptst.executeQuery();
           DefaultTableModel model = (DefaultTableModel)table.getModel();
           model.setRowCount(0);
           while(rs.next()){
            model.addRow(new String[] {rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
        }
           c.close();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(orderUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
    }
    
        public void showtable2(String name)
    {
        try {
            // TODO add your handling code here:
            String s = "Completed";
           Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sp","root","15177");
           String sql = "select *from up where user = ? and status = ? order by date desc";
           PreparedStatement ptst = c.prepareStatement(sql);
           ptst.setString(1, name);
           ptst.setString(2, s);
           ResultSet rs = ptst.executeQuery();
           DefaultTableModel model = (DefaultTableModel)table1.getModel();
           model.setRowCount(0);
           while(rs.next()){
            model.addRow(new String[] {rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
        }
           c.close();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(orderUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
    }
        
    public orderUser() {
        initComponents();
    } 
    public orderUser(String n) {
        initComponents();
        name = n;
        showtable(name);
        showtable2(name);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new rojeru_san.complementos.RSTableMetro();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new rojeru_san.complementos.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 35, 35));
        jLabel3.setText("*click on the row to cancel order");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(86, 2, 45));
        jLabel4.setText(" At Your Service");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service name", "Service Charge", "Expected Date", "Expected Time", "Address", "Priority", "Description", "Status"
            }
        ));
        table.setColorBackgoundHead(new java.awt.Color(100, 2, 51));
        table.setColorBordeFilas(new java.awt.Color(102, 0, 51));
        table.setColorBordeHead(new java.awt.Color(102, 0, 51));
        table.setColorFilasBackgound2(new java.awt.Color(229, 162, 173));
        table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        table.setColorSelBackgound(new java.awt.Color(153, 0, 51));
        table.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        table.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setRowHeight(60);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(129, 2, 45));
        jLabel5.setText("In process services: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 51));
        jLabel6.setText("Completed Services :");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service name", "Service Charge", "Expected Date", "Expected Time", "Address", "Priority", "Description", "Status"
            }
        ));
        table1.setColorBackgoundHead(new java.awt.Color(102, 0, 51));
        table1.setColorBordeFilas(new java.awt.Color(102, 0, 51));
        table1.setColorBordeHead(new java.awt.Color(102, 0, 51));
        table1.setColorFilasBackgound2(new java.awt.Color(221, 169, 178));
        table1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        table1.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        table1.setColorSelBackgound(new java.awt.Color(153, 0, 51));
        table1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        table1.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table1.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table1.setGridColor(new java.awt.Color(255, 255, 255));
        table1.setRowHeight(60);
        table1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(table1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic2/arrow-121-24.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic2/minus-24.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(474, 474, 474)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        TableModel model = table.getModel();
        
        //String status = model.getValueAt(index, 7).toString();
        String Service = model.getValueAt(index, 0).toString();
        
        String status = "Canceled";
        int a = JOptionPane.showConfirmDialog(null,"Are you sure you want to cancel your order? ","select",JOptionPane.YES_NO_OPTION );
        if(a==0){
            try {
            // TODO add your handling code here:

           Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sp","root","15177");
           String sql = "update up set status=? where user=? and service=? and (status=? or status=?) ";
           PreparedStatement ptst = c.prepareStatement(sql);
           ptst.setString(2, name);
           ptst.setString(4, "Requested");
           ptst.setString(5, "Assigned");
           ptst.setString(1, status);
           ptst.setString(3, Service);
           ptst.executeUpdate();
           JOptionPane.showMessageDialog(this, "Canceled!!!");
           showtable(name);
           c.close();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(orderUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         String wid = null;
         try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("select *from up where user=? and status = ? and Service = ?");
            pst.setString(1, name);
            pst.setString(2, "Canceled");
            pst.setString(3, Service);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                wid = rs.getString("workerid");
                String sql = "update workers set status=? where id=?";
                PreparedStatement ptst = con.prepareStatement(sql);
                ptst.setString(2, wid);
                ptst.setString(1, "Free");
                ptst.executeUpdate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       setVisible(false);
       new Home(name).setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(orderUser.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.complementos.RSTableMetro table;
    private rojeru_san.complementos.RSTableMetro table1;
    // End of variables declaration//GEN-END:variables
}
