

import dd.ConnectionProvider;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rubai
 */
public class Workers extends javax.swing.JFrame {

    public void load()
    {
         try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("select service_name from services");

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("service_name");
                c_service.addItem(name);
                c_service1.addItem(name);
                c_service2.addItem(name);
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void load2()
    {
        String sname2 = c_service2.getSelectedItem().toString();
        c_worker3.removeAllItems();
         try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement ptst = con.prepareStatement("select name from workers where Service = ? and Status = ?");
            ptst.setString(1, sname2);
            ptst.setString(2, "Free");
            ResultSet rs = ptst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("name");
                c_worker3.addItem(name);
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showtable()
    {
        String sname1 = c_service1.getSelectedItem().toString();
        try {
            // TODO add your handling code here:

           Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sp","root","15177");
           String sql = "select *from workers where Service = ?";
           PreparedStatement ptst = c.prepareStatement(sql);
           ptst.setString(1, sname1);
           ResultSet rs = ptst.executeQuery();
           DefaultTableModel model = (DefaultTableModel)table.getModel();
           model.setRowCount(0);
           while(rs.next()){
            model.addRow(new String[] {rs.getString(1),rs.getString(2),rs.getString(4),rs.getString(6),rs.getString(5)});
        }
           c.close();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
    }
        public void showtable2()
    {
        String sname3 = c_service2.getSelectedItem().toString();
        try {
            // TODO add your handling code here:

           Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sp","root","15177");
           String sql = "select *from up where status=? and service = ? order by date";
           PreparedStatement ptst = c.prepareStatement(sql);
           ptst.setString(1, "Requested");
           ptst.setString(2, sname3);
           ResultSet rs = ptst.executeQuery();
           DefaultTableModel model = (DefaultTableModel)table1.getModel();
           model.setRowCount(0);
           while(rs.next()){
            model.addRow(new String[] {rs.getString(2),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(10)});
        }
           c.close();
        } 
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(AdminService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
    }
    public Workers() {
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        wname = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        exp = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();
        c_service = new javax.swing.JComboBox<>();
        txtMobile = new app.bolivia.swing.JCTextField();
        jLabel_repass = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        c_service1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new rojeru_san.complementos.RSTableMetro();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        c_service2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new rojeru_san.complementos.RSTableMetro();
        jLabel11 = new javax.swing.JLabel();
        c_worker3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" At Your Service");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("-");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(430, 430, 430)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic2/worker.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wname.setBackground(new java.awt.Color(242, 242, 242));
        wname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        wname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        wname.setPlaceholder("Enter name");
        wname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wnameActionPerformed(evt);
            }
        });
        wname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wnameKeyReleased(evt);
            }
        });
        jPanel6.add(wname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 320, 43));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guest-32.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 37, -1));

        exp.setBackground(new java.awt.Color(242, 242, 242));
        exp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        exp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        exp.setPlaceholder("Enter Experience");
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });
        exp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expKeyReleased(evt);
            }
        });
        jPanel6.add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 320, 43));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic2/icons8-popular-man-48.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic2/icons8-service-40.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 40, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutPic/user_1.png"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(101, 8, 84));
        rSMaterialButtonRectangle1.setText("Add");
        rSMaterialButtonRectangle1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel6.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 340, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutPic/pp.jpg"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 513, -1));

        c_service.setBackground(new java.awt.Color(242, 242, 242));
        c_service.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        c_service.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add here-->" }));
        c_service.setOpaque(true);
        c_service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c_serviceMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                c_serviceMouseReleased(evt);
            }
        });
        c_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_serviceActionPerformed(evt);
            }
        });
        c_service.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_serviceKeyReleased(evt);
            }
        });
        jPanel6.add(c_service, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 320, 40));

        txtMobile.setBackground(new java.awt.Color(242, 242, 242));
        txtMobile.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMobile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtMobile.setPlaceholder("Enter Phone Number");
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobileKeyReleased(evt);
            }
        });
        jPanel6.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 320, 40));

        jLabel_repass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phone-28-32.png"))); // NOI18N
        jPanel6.add(jLabel_repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        jTabbedPane1.addTab("Add Worker", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c_service1.setBackground(new java.awt.Color(242, 242, 242));
        c_service1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        c_service1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add here-->" }));
        c_service1.setOpaque(true);
        c_service1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_service1MouseClicked(evt);
            }
        });
        c_service1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_service1ActionPerformed(evt);
            }
        });
        jPanel7.add(c_service1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 320, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        jLabel8.setText("Service name");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 45, -1, 33));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Worker ID", "Name", "Experience", "Contact no", "Status"
            }
        ));
        table.setColorBackgoundHead(new java.awt.Color(101, 8, 84));
        table.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        table.setColorBordeHead(new java.awt.Color(101, 8, 84));
        table.setColorFilasBackgound2(new java.awt.Color(227, 201, 222));
        table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        table.setColorSelBackgound(new java.awt.Color(6, 143, 143));
        table.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        table.setFuenteFilas(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        table.setFuenteFilasSelect(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        table.setFuenteHead(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        table.setRowHeight(50);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 1260, 420));

        jLabel12.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(101, 8, 84));
        jLabel12.setText("*Click on the row to delete worker");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 330, -1));

        jTabbedPane1.addTab("See Worker", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        jLabel9.setText("Service name");

        c_service2.setBackground(new java.awt.Color(242, 242, 242));
        c_service2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        c_service2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add here-->" }));
        c_service2.setOpaque(true);
        c_service2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_service2MouseClicked(evt);
            }
        });
        c_service2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_service2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Requested Services :");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Expected Date", "Expected Time", "Address", "Priority", "Status"
            }
        ));
        table1.setColorBordeFilas(new java.awt.Color(153, 204, 255));
        table1.setColorBordeHead(new java.awt.Color(0, 0, 204));
        table1.setColorFilasBackgound2(new java.awt.Color(177, 223, 246));
        table1.setColorSelBackgound(new java.awt.Color(6, 143, 143));
        table1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        table1.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table1.setGridColor(new java.awt.Color(255, 255, 255));
        table1.setRowHeight(80);
        table1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        jLabel11.setText("Available Worker: ");

        c_worker3.setBackground(new java.awt.Color(242, 242, 242));
        c_worker3.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        c_worker3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add here-->" }));
        c_worker3.setOpaque(true);
        c_worker3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_worker3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(101, 8, 84));
        jLabel13.setText("*Click on the row to whom you want to assign the worker");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_worker3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_service2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel9)))
                        .addGap(604, 604, 604))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(678, 678, 678))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(c_service2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_worker3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assign Worker", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new AdminHome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(confirm.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wnameActionPerformed

    private void wnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wnameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_wnameKeyReleased

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expActionPerformed

    private void expKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_expKeyReleased

    public void clear()
    {
        wname.setText("");
        exp.setText("");
        txtMobile.setText("");
        
    }
    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
        String sname = c_service.getSelectedItem().toString();
        try {
           
           Connection c = ConnectionProvider.getcon();
           String sql = "insert into workers (name,Service,Experience,Status,phone) values(?,?,?,?,?)";
           PreparedStatement ptst = c.prepareStatement(sql);
           ptst.setString(1,wname.getText());
           ptst.setString(2, sname);
           ptst.setString(3, exp.getText());
           ptst.setString(4, "Free");
           ptst.setString(5, txtMobile.getText());
           ptst.executeUpdate();
           JOptionPane.showMessageDialog(this, "Worker Added!");
            clear();
           c.close();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void c_serviceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_serviceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c_serviceMouseEntered

    private void c_serviceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_serviceMouseReleased

    }//GEN-LAST:event_c_serviceMouseReleased

    private void c_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_serviceActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_c_serviceActionPerformed

    private void c_serviceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_serviceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_c_serviceKeyReleased

    private void c_service1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_service1ActionPerformed
        // TODO add your handling code here:
        showtable();
    }//GEN-LAST:event_c_service1ActionPerformed

    private void c_service1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_service1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c_service1MouseClicked

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileKeyReleased

    private void c_service2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_service2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c_service2MouseClicked

    private void c_service2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_service2ActionPerformed
        // TODO add your handling code here:
        load2();
        showtable2();
    }//GEN-LAST:event_c_service2ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        
        int index = table1.getSelectedRow();
        TableModel model = table1.getModel();
        String email = model.getValueAt(index,0).toString();
        String Service = c_service2.getSelectedItem().toString();
        String status = model.getValueAt(index, 5).toString();
        String wname = c_worker3.getSelectedItem().toString();

        if(status.equals("Requested")){
            status = "Assigned";
        }
        int a = JOptionPane.showConfirmDialog(null,"Do you want to assign "+wname+" to "+email+"","select",JOptionPane.YES_NO_OPTION );
        if(a==0){
            String wid = null;
         try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("select *from workers where name = ? and Service = ?");
            pst.setString(1, wname);
            pst.setString(2, Service);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                wid = rs.getString("id");
                String sql = "update up set workerid=? where user=? and service=? and status=?";
                PreparedStatement ptst = con.prepareStatement(sql);
                ptst.setString(2, email);
                ptst.setString(1, wid);
                ptst.setString(3, Service);
                ptst.setString(4, "Requested");
                ptst.executeUpdate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
                // TODO add your handling code here:

                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sp","root","15177");
                String sql = "update up set status=? where user=? and service=? and status=?";
                PreparedStatement ptst = c.prepareStatement(sql);
                ptst.setString(2, email);
                ptst.setString(1, status);
                ptst.setString(3, Service);
                ptst.setString(4, "Requested");
                ptst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Worker Assigned");
                //showtable();
                showtable2();
                c.close();
            } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            try {
                // TODO add your handling code here:

                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sp","root","15177");
                String sql = "update workers set status=? where name=? and service=?";
                PreparedStatement ptst = c.prepareStatement(sql);
                ptst.setString(2,wname);
                ptst.setString(1, "Assigned");
                ptst.setString(3, Service);
                ptst.executeUpdate();
                load2();
                c.close();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_table1MouseClicked

    private void c_worker3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_worker3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_worker3ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        TableModel model = table.getModel();
        String name = model.getValueAt(index,0).toString();
        String sename = c_service1.getSelectedItem().toString();
        
        int a = JOptionPane.showConfirmDialog(null,"Do you want to remove "+name+" as worker??","select",JOptionPane.YES_NO_OPTION );
        if(a==0){
         try {
            Connection con = ConnectionProvider.getcon();
           String sql = "delete from workers where name=? and Service = ?";
           PreparedStatement ptst = con.prepareStatement(sql);
           ptst.setString(1,name);
           ptst.setString(2,sename);
           ptst.executeUpdate();
           JOptionPane.showMessageDialog(this, "Worker Removed !");
           showtable();
           con.close();
         }
         catch (SQLException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c_service;
    private javax.swing.JComboBox<String> c_service1;
    private javax.swing.JComboBox<String> c_service2;
    private javax.swing.JComboBox<String> c_worker3;
    private app.bolivia.swing.JCTextField exp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_repass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojeru_san.complementos.RSTableMetro table;
    private rojeru_san.complementos.RSTableMetro table1;
    private app.bolivia.swing.JCTextField txtMobile;
    private app.bolivia.swing.JCTextField wname;
    // End of variables declaration//GEN-END:variables
}
